[project]
name = "braintrust-eval-101-course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "yogibdoodle-code", email = "yogibdoodle@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "braintrust>=0.37.0",
    "anthropic>=0.43.0",
    "autoevals>=0.1.0",
    "python-dotenv>=1.0.0",
    "openai>=3.8.0",
]

[project.scripts]
braintrust-eval-101-course = "braintrust_eval_101_course:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
